# Generated by Django 3.2.23 on 2024-01-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.associatecompany'),
        ),
    ]
