# Generated by Django 3.2.23 on 2024-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20240131_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
