# Generated by Django 3.2.23 on 2024-02-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20240201_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
