# Generated by Django 3.2.23 on 2024-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_shipment_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatecompany',
            name='associate_company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='associatecompany',
            name='associate_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
