# Generated by Django 3.2.23 on 2024-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20240209_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
