# Generated by Django 3.2.23 on 2024-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_shipment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pickedup_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
