# Generated by Django 3.2.23 on 2024-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_shipment_pickedup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='pickedup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
