# Generated by Django 3.2.23 on 2024-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_alter_shipment_pickedup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Assigned', 'Assigned'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered'), ('Returned Empty', 'Returned Empty')], max_length=20),
        ),
    ]
