# Generated by Django 3.2.23 on 2024-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
