# Generated by Django 3.2.23 on 2024-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_company_company_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatecompany',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
