# Generated by Django 3.2.23 on 2024-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20240226_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='proof_of_delivery_file',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_delivery/'),
        ),
    ]
