# Generated by Django 3.2.23 on 2024-03-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240223_1030'),
        ('backoffice', '0019_shipment_proof_of_delivery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='users.driver'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='users.warehouseuser'),
        ),
    ]
