# Generated by Django 3.2.23 on 2024-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_auto_20240319_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
