# Generated by Django 3.2.23 on 2024-03-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20240329_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='driver_delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
