# Generated by Django 3.2.23 on 2024-03-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_auto_20240329_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associatecompany',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
