# Generated by Django 3.2.23 on 2024-01-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
        ('users', '0005_user_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='backofficeuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backoffice_users', to='backoffice.company'),
        ),
    ]
