# Generated by Django 3.2.23 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240123_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('backoffice', 'Backoffice'), ('warehouse', 'Warehouse'), ('driver', 'Driver')], max_length=15),
        ),
    ]
