# Generated by Django 3.2.23 on 2024-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dg_certification',
            field=models.CharField(max_length=20),
        ),
    ]
