# Generated by Django 3.2.23 on 2024-01-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_shipment_customer'),
        ('users', '0009_alter_driver_dg_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_users', to='backoffice.company'),
        ),
    ]
