# Generated by Django 3.2.23 on 2024-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
